import Button from "react-bootstrap/Button";
import Modal from "react-bootstrap/Modal";
import { XCircle } from "react-bootstrap-icons";
import { ModalProps } from "../types";

const InstructionsModal: React.FC<ModalProps> = ({ onClose, show }) => {
  return (
    <>
      <Modal show={show} onHide={onClose} id="instructions" size="lg">
        <Modal.Header closeButton>
          <Modal.Title>Set Creator Instructions</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <p className="warning">
            This web app is for larger devices only. As it's a PC modding tool,
            it may not display well mobile.
          </p>
          <h5>Steps:</h5>
          <ol>
            <li>
              Download the tutorial PDF and template files from the
              Miscellaneous section:{" "}
              <a
                href="https://www.nexusmods.com/baldursgate3/mods/5907?tab=files"
                target="_blank"
              >
                Modder's Resource
              </a>
            </li>
            <li>
              Use the app to choose which piercings you want to include in your
              set
            </li>
            <li>
              Click the VIEW CURRENT SET button at the top right to check your
              set or when you're finished choosing piercings to get the code.
            </li>
            <li>
              At the bottom of the modal, click the 'Generate Piercing Nodes'
              button to generate the code, which you will copy and paste into
              your CCAS file
            </li>
          </ol>
          <h5>Disclaimer:</h5>
          <p>
            Please be aware and careful when editing the replacer files, you are
            modding your game. The code generated by the app works - but small
            errors when you copy and paste may result in something breaking. For
            example: missing a closing &lt;/children&gt; tag may make your Body
            Art tab disappear
          </p>
          <p>
            If you find that something isn't working after placing your template
            into the game's folder, then there is an error in your CCAS file.
          </p>
          <h5>Notes:</h5>
          <p>
            If you include mod piercings, you will need to have the mod(s)
            installed or the piercings will not show. The app will display a
            link to any mods in your set after generating the code.
          </p>
          <p>
            If you're having trouble or need some help, please visit{" "}
            <a href="https://discord.com/invite/downbytheriver" target="_blank">
              Down By The River
            </a>{" "}
            on Discord and ask :)
          </p>
        </Modal.Body>
        <Modal.Footer className="d-flex justify-content-between">
          <Button
            variant="secondary"
            className="btn-secondary"
            onClick={onClose}
            data-testid="btn-close"
          >
            <XCircle /> Close
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
};

export default InstructionsModal;
