export const data = [
  {
    index: 1,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Fang",
    pt_bone: "Lobe Upper (R)",
    bone: "piercing_lobe_b_r",
    location: "ears",
    nodeid: "76df94f8-bb0e-4fc7-9ce5-a666f2f47a06",
    imgurl: "assets/images/barb-bear-fang.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 2,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Claw",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "2f48a311-325a-4303-83cd-121df9ca6c3b",
    imgurl: "assets/images/barb-bear-claw.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 3,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Fang",
    pt_bone: "Lobe Upper (L)",
    bone: "piercing_lobe_b_l",
    location: "ears",
    nodeid: "f8f94018-6b34-43ed-a3fd-31392864fba0",
    imgurl: "assets/images/barb-bear-fang.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 4,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Claw",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "f91fcab5-e4ab-40b9-9e45-d73913288ace",
    imgurl: "assets/images/barb-bear-claw.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 5,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Brow Scales",
    pt_bone: "Brow Lower (R)",
    bone: "piercing_brow_b_r",
    location: "brows",
    nodeid: "923cab0e-9ba4-4bc9-9fbf-c4c661dd6f43",
    imgurl: "assets/images/barb-bear-scales.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 6,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Brow Scales",
    pt_bone: "Brow Lower (L)",
    bone: "piercing_brow_b_l",
    location: "brows",
    nodeid: "7a18be45-1186-4753-99b8-86700df3b2d6",
    imgurl: "assets/images/barb-bear-scales.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 7,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Skull Ring",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "5637952a-dd79-4803-bb91-732606917c7d",
    imgurl: "assets/images/barb-bear-skull-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 8,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Brow Stubs",
    pt_bone: "Brow Upper (R)",
    bone: "piercing_brow_a_r",
    location: "brows",
    nodeid: "6e9e5bb1-68b1-41a2-b22d-e117151abec6",
    imgurl: "assets/images/barb-bear-stubs-r.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 9,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Brow Stubs",
    pt_bone: "Brow Upper (L)",
    bone: "piercing_brow_a_l",
    location: "brows",
    nodeid: "9f144714-747f-4a8d-b9c8-72da46813606",
    imgurl: "assets/images/barb-bear-stubs-l.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 10,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Ring",
    pt_bone: "Helix Upper (L)",
    bone: "piercing_helix_a_l",
    location: "ears",
    nodeid: "3458671f-d345-47b7-aed9-33acaa7d9140",
    imgurl: "assets/images/barb-bear-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 11,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Ring",
    pt_bone: "Helix Upper (R)",
    bone: "piercing_helix_a_r",
    location: "ears",
    nodeid: "0f5ad7fc-9c12-417d-8a5a-74cfa402d08a",
    imgurl: "assets/images/barb-bear-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 12,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Bridge Pad",
    pt_bone: "Bridge (R)",
    bone: "piercing_bridge_a_r",
    location: "nose",
    nodeid: "e5d21d17-52e3-4c0b-a791-d6bb513810dc",
    imgurl: "assets/images/barb-bear-bridge-r.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 13,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Bear",
    color: "silver",
    name: "Bear Bridge Pad",
    pt_bone: "Bridge (L)",
    bone: "piercing_bridge_a_l",
    location: "nose",
    nodeid: "488764f9-d69a-4c70-a837-aa9e15059410",
    imgurl: "assets/images/barb-bear-bridge-l.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-bear",
    matid: "95004272-96ad-9967-9bb3-6b556d3bcbed",
  },
  {
    index: 14,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Eagle",
    color: "silver",
    name: "Eagle Feathers Ring",
    pt_bone: "Brow Lower (L)",
    bone: "piercing_brow_b_l",
    location: "brows",
    nodeid: "0c50da5c-4d98-44cd-bd7b-dad6fb56e302",
    imgurl: "assets/images/barb-eagle-feathers.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-eagle",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32205",
  },
  {
    index: 15,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Eagle",
    color: "silver",
    name: "Eagle Feathers Ring",
    pt_bone: "Brow Lower (R)",
    bone: "piercing_brow_b_r",
    location: "brows",
    nodeid: "2ab1b724-e135-4201-84b5-f10718aaf49c",
    imgurl: "assets/images/barb-eagle-feathers.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-eagle",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32206",
  },
  {
    index: 16,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Eagle",
    color: "silver",
    name: "Eagle Wing Ring",
    pt_bone: "Nostril (L)",
    bone: "piercing_nostril_a_l",
    location: "nose",
    nodeid: "2bbfc373-6f7a-41d6-8195-49799e1fca5b",
    imgurl: "assets/images/barb-eagle-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-eagle",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32207",
  },
  {
    index: 17,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Eagle",
    color: "silver",
    name: "Eagle Talon Dangle",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "f32e763d-d06a-4446-a0be-4f8c6e59c9ef",
    imgurl: "assets/images/barb-eagle-talon.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-eagle",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32208",
  },
  {
    index: 18,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Eagle",
    color: "silver",
    name: "Eagle Talon Dangle",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "d65b5840-af18-4d2e-86ac-667151b504b0",
    imgurl: "assets/images/barb-eagle-talon.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-eagle",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32209",
  },
  {
    index: 19,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Eagle",
    color: "silver",
    name: "Eagle Wing Stud",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "a98c28e5-7fca-4970-a72d-a14de5569a10",
    imgurl: "assets/images/barb-eagle-wing-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-eagle",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32210",
  },
  {
    index: 20,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Eagle",
    color: "silver",
    name: "Eagle Wing Stud",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "6d243492-db25-4858-8a92-2bd9301ad7d2",
    imgurl: "assets/images/barb-eagle-wing-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-eagle",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32211",
  },
  {
    index: 21,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Eagle",
    color: "silver",
    name: "Eagle Crest Ring",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "035ae250-e1d3-4455-9ab4-6251ff8ea9a8",
    imgurl: "assets/images/barb-eagle-crest-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-eagle",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32212",
  },
  {
    index: 22,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Skull/Teeth Ring",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "4d1ffd7d-e712-4f72-b058-5fb7b692e1f0",
    imgurl: "assets/images/barb-wolf-skull-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18624",
  },
  {
    index: 23,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Claw Small",
    pt_bone: "Helix Lower (R)",
    bone: "piercing_helix_b_r",
    location: "ears",
    nodeid: "10c857a3-a99c-4bf3-9530-11f9ff5f6051",
    imgurl: "assets/images/barb-wolf-claw-sm-hl.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18628",
  },
  {
    index: 24,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Claw Small",
    pt_bone: "Helix Upper (R)",
    bone: "piercing_helix_a_r",
    location: "ears",
    nodeid: "c865951b-cd3f-49d3-87d4-cdb6327fe482",
    imgurl: "assets/images/barb-wolf-claw-sm-hu.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18625",
  },
  {
    index: 25,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Claw Small",
    pt_bone: "Helix Lower (L)",
    bone: "piercing_helix_b_l",
    location: "ears",
    nodeid: "ccb0dd23-1c70-4f7d-9131-613458338c55",
    imgurl: "assets/images/barb-wolf-claw-sm-hl.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18626",
  },
  {
    index: 26,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Claw Small",
    pt_bone: "Helix Upper (L)",
    bone: "piercing_helix_a_l",
    location: "ears",
    nodeid: "fc596209-7264-4e43-b4fc-4718e7a2c14a",
    imgurl: "assets/images/barb-wolf-claw-sm-hu.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18627",
  },
  {
    index: 27,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Claw Large",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "1c62a50a-5871-43a5-afac-460e48597404",
    imgurl: "assets/images/barb-wolf-claw-l.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18629",
  },
  {
    index: 28,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Claw Large",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "cd8be905-03f5-4e0f-a4e6-de68ae6f714e",
    imgurl: "assets/images/barb-wolf-claw-l.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18630",
  },
  {
    index: 29,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Branch",
    pt_bone: "Brow Upper (R)",
    bone: "piercing_brow_a_r",
    location: "brows",
    nodeid: "dc5d9502-9296-4c67-b01a-b2a772fe6b19",
    imgurl: "assets/images/barb-wolf-branch.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18631",
  },
  {
    index: 30,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Branch",
    pt_bone: "Brow Upper (L)",
    bone: "piercing_brow_a_l",
    location: "brows",
    nodeid: "20cd941c-8f09-4e53-8a31-8457e5edd22b",
    imgurl: "assets/images/barb-wolf-branch.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18632",
  },
  {
    index: 31,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Sphere",
    pt_bone: "Brow Lower (L)",
    bone: "piercing_brow_b_l",
    location: "brows",
    nodeid: "98c958a9-efca-4129-8d91-6b963aee979a",
    imgurl: "assets/images/barb-wolf-sphere.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18633",
  },
  {
    index: 32,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Wolf",
    color: "silver",
    name: "Wolf Sphere",
    pt_bone: "Brow Lower (R)",
    bone: "piercing_brow_b_r",
    location: "brows",
    nodeid: "2815ff06-f464-4d2f-8450-a2fdabd38ca1",
    imgurl: "assets/images/barb-wolf-sphere.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-wolf",
    matid: "e6818c29-219c-9d87-f927-d19c4ae18634",
  },
  {
    index: 33,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Tiger",
    color: "silver",
    name: "Tiger Gem Stud",
    pt_bone: "Brow Upper (L)",
    bone: "piercing_brow_a_l",
    location: "brows",
    nodeid: "91d66a20-6421-4385-b445-f19e3285b7fd",
    imgurl: "assets/images/barb-tiger-gem.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-tiger",
    matid: "b2ebb4dd-dd10-479c-0692-1aa21568fd84",
  },
  {
    index: 34,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Tiger",
    color: "silver",
    name: "Tiger Gem Stud",
    pt_bone: "Brow Upper (R)",
    bone: "piercing_brow_a_r",
    location: "brows",
    nodeid: "f066fd0a-051e-4cd9-83b8-05cbc1ef4bfe",
    imgurl: "assets/images/barb-tiger-gem.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-tiger",
    matid: "b2ebb4dd-dd10-479c-0692-1aa21568fd85",
  },
  {
    index: 35,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Tiger",
    color: "silver",
    name: "Tiger Claw Dangle",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "5b3d0097-b30b-4a60-bc09-97c1bcf215bd",
    imgurl: "assets/images/barb-tiger-claw.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-tiger",
    matid: "b2ebb4dd-dd10-479c-0692-1aa21568fd86",
  },
  {
    index: 36,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Tiger",
    color: "silver",
    name: "Tiger Claw Dangle",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "36cc29e9-6aba-460c-bc64-f78004c644b7",
    imgurl: "assets/images/barb-tiger-claw.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-tiger",
    matid: "b2ebb4dd-dd10-479c-0692-1aa21568fd87",
  },
  {
    index: 37,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Tiger",
    color: "silver",
    name: "Tiger Tooth Spike",
    pt_bone: "Bridge (L)",
    bone: "piercing_bridge_a_l",
    location: "nose",
    nodeid: "a7804e00-efdc-4871-95a7-66e6ae2ea62d",
    imgurl: "assets/images/barb-tiger-spike-br-l.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-tiger",
    matid: "b2ebb4dd-dd10-479c-0692-1aa21568fd88",
  },
  {
    index: 38,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Tiger",
    color: "silver",
    name: "Tiger Tooth Spike",
    pt_bone: "Bridge (R)",
    bone: "piercing_bridge_a_r",
    location: "nose",
    nodeid: "f615a68b-3fe3-4d21-a0ae-544876578f25",
    imgurl: "assets/images/barb-tiger-spike-br-r.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-tiger",
    matid: "b2ebb4dd-dd10-479c-0692-1aa21568fd89",
  },
  {
    index: 39,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Tiger",
    color: "silver",
    name: "Tiger Tooth Spike",
    pt_bone: "Nostril (L)",
    bone: "piercing_nostril_a_l",
    location: "nose",
    nodeid: "6b50f00d-ab88-40de-bbae-0c870ef96628",
    imgurl: "assets/images/barb-tiger-spike-no-l.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-tiger",
    matid: "b2ebb4dd-dd10-479c-0692-1aa21568fd90",
  },
  {
    index: 40,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Tiger",
    color: "silver",
    name: "Tiger Tooth Spike",
    pt_bone: "Nostril (R)",
    bone: "piercing_nostril_a_r",
    location: "nose",
    nodeid: "c2645a3e-516b-4ceb-8cd3-c303e86f8cff",
    imgurl: "assets/images/barb-tiger-spike-no-r.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-tiger",
    matid: "b2ebb4dd-dd10-479c-0692-1aa21568fd91",
  },
  {
    index: 41,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Elk",
    color: "silver",
    name: "Elk Antler",
    pt_bone: "Brow Lower (L)",
    bone: "piercing_brow_b_l",
    location: "brows",
    nodeid: "24a99cc2-6845-41ea-a7e7-5e0c2ece1dc8",
    imgurl: "assets/images/barb-elk-antler.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-elk",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32205",
  },
  {
    index: 42,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Elk",
    color: "silver",
    name: "Elk Antler",
    pt_bone: "Brow Lower (R)",
    bone: "piercing_brow_b_r",
    location: "brows",
    nodeid: "8fdbf362-c8ef-44ea-b476-eac96e4b0d88",
    imgurl: "assets/images/barb-elk-antler.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-elk",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32206",
  },
  {
    index: 43,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Elk",
    color: "silver",
    name: "Elk Flat Stud",
    pt_bone: "Nostril (L)",
    bone: "piercing_nostril_a_l",
    location: "nose",
    nodeid: "e6f20c91-cfe6-40b0-a5c9-6ee8805580e3",
    imgurl: "assets/images/barb-elk-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-elk",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32207",
  },
  {
    index: 44,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Elk",
    color: "silver",
    name: "Elk Flat Stud",
    pt_bone: "Nostril (R)",
    bone: "piercing_nostril_a_r",
    location: "nose",
    nodeid: "c984b9b9-c483-4413-90e9-f5820243c7d5",
    imgurl: "assets/images/barb-elk-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-elk",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32208",
  },
  {
    index: 45,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Elk",
    color: "silver",
    name: "Elk Wood Hoop",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "0c52811a-a5de-49c5-b36d-5d27da5b8d09",
    imgurl: "assets/images/barb-elk-wood-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-elk",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32209",
  },
  {
    index: 46,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Elk",
    color: "silver",
    name: "Elk Wood Hoop",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "27e94952-9ea8-4954-b2f6-7ac5b2565e9a",
    imgurl: "assets/images/barb-elk-wood-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-elk",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32210",
  },
  {
    index: 47,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Elk",
    color: "silver",
    name: "Elk Skull Ring",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "39eca6d3-7dad-4b56-a77b-dc6618e62f84",
    imgurl: "assets/images/barb-elk-skull.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-elk",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32211",
  },
  {
    index: 48,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Elk",
    color: "silver",
    name: "Elk Sphere",
    pt_bone: "Brow Upper (L)",
    bone: "piercing_brow_a_l",
    location: "brows",
    nodeid: "18b289b9-ec9e-4812-a5d6-329a941ae4db",
    imgurl: "assets/images/barb-elk-sphere.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-elk",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32212",
  },
  {
    index: 49,
    site_cat: "barbarian",
    type: "vanilla",
    set_name: "Barbarian - Elk",
    color: "silver",
    name: "Elk Sphere",
    pt_bone: "Brow Upper (R)",
    bone: "piercing_brow_a_r",
    location: "brows",
    nodeid: "4bf1110e-adfc-4ccf-ad5a-788fc0958cdf",
    imgurl: "assets/images/barb-elk-sphere.jpg",
    selected: false,
    disabled: false,
    matcat: "barb-elk",
    matid: "bd069145-fbc8-3fbc-befc-a3de9ea32213",
  },
  {
    index: 50,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Fastened Stars",
    color: "silver",
    name: "Ring with Spikes",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "840aac96-fc21-4f7a-95e0-bbdd99f2e8fd",
    imgurl: "assets/images/van-ring-spikes.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 51,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Fastened Stars",
    color: "silver",
    name: "Vanilla Ball Stud",
    pt_bone: "Brow Upper (R)",
    bone: "piercing_brow_a_r",
    location: "brows",
    nodeid: "8231239f-2dcd-477e-8b23-86dab0f4318f",
    imgurl: "assets/images/van-ball-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 52,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Fastened Stars",
    color: "silver",
    name: "Ring with Spikes",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "a5c9175c-a997-4792-a606-64b9a2774c5b",
    imgurl: "assets/images/van-ring-spikes.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 53,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Fastened Stars",
    color: "silver",
    name: "Vanilla Ball Stud ",
    pt_bone: "Brow Lower (R)",
    bone: "piercing_brow_b_r",
    location: "brows",
    nodeid: "d4346eaa-656d-4ff4-8382-f940faa92965",
    imgurl: "assets/images/van-ball-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 54,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Lapis Studmuffin",
    color: "silver",
    name: "Sapphire & Chain",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "a7f42b00-7f14-4137-8665-5bbe986b1bdf",
    imgurl: "assets/images/van-sapphire-chain.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 55,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Lapis Studmuffin",
    color: "silver",
    name: "Sapphire & Chain",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "0311cf7a-3fa4-4b05-a608-4716d54c36a4",
    imgurl: "assets/images/van-sapphire-chain.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 56,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Lapis Studmuffin",
    color: "silver",
    name: "Vanilla Flat Ring",
    pt_bone: "Helix Lower (L)",
    bone: "piercing_helix_b_l",
    location: "ears",
    nodeid: "c3eb8b5e-b5eb-4b50-9c49-058e74439656",
    imgurl: "assets/images/van-flat-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 57,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Subduer Loops",
    color: "silver",
    name: "Spiral Swirl",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "b647514a-04f7-4be4-a3a3-e7f9d786e303",
    imgurl: "assets/images/van-spiral-swirl.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 58,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Subduer Loops",
    color: "silver",
    name: "Spiral Swirl",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "adcde0f3-3f4e-4e03-8e21-5685e3723bbf",
    imgurl: "assets/images/van-spiral-swirl.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 59,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Subduer Loops",
    color: "silver",
    name: "Brow Cuff",
    pt_bone: "Brow Upper (L)",
    bone: "piercing_brow_a_l",
    location: "brows",
    nodeid: "1721a058-0e06-471d-845d-7305ca88f44f",
    imgurl: "assets/images/van-brow-cuff.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 60,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Subduer Loops",
    color: "silver",
    name: "Brow Cuff",
    pt_bone: "Brow Upper (R)",
    bone: "piercing_brow_a_r",
    location: "brows",
    nodeid: "5c9bc416-de0d-4d6f-8be4-24beaf0099e4",
    imgurl: "assets/images/van-brow-cuff.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 61,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Subduer Loops",
    color: "silver",
    name: "Spike Barbell",
    pt_bone: "Helix Upper (L)",
    bone: "piercing_helix_a_l",
    location: "ears",
    nodeid: "ba42b168-d64c-4101-bc5d-3ae77bb93eb3",
    imgurl: "assets/images/van-dblspike-bb.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 62,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Subduer Loops",
    color: "silver",
    name: "Spike Barbell",
    pt_bone: "Helix Lower (L)",
    bone: "piercing_helix_b_l",
    location: "ears",
    nodeid: "045a5fc3-1b43-403d-afe4-efc8faaa082a",
    imgurl: "assets/images/van-dblspike-bb-lu.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 63,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Subduer Loops",
    color: "silver",
    name: "Triangle Stud",
    pt_bone: "Nostril (R)",
    bone: "piercing_nostril_a_r",
    location: "nose",
    nodeid: "ab6e3f94-c481-4cd4-8e01-d7d42f8b0579",
    imgurl: "assets/images/van-triangle-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 64,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Subduer Loops",
    color: "silver",
    name: "Spike Barbell",
    pt_bone: "Helix Lower (R)",
    bone: "piercing_helix_b_r",
    location: "ears",
    nodeid: "35b7f0c1-1ed0-4303-b90a-a1f4066b4523",
    imgurl: "assets/images/van-dblspike-bb-ll.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 65,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Midnight Tears",
    color: "silver",
    name: "Bird Skull",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "0f9151e8-c340-4f02-a87e-4ea8947f9511",
    imgurl: "assets/images/van-bird-skull.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 66,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Midnight Tears",
    color: "silver",
    name: "Bird Skull",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "32df873d-fab9-4dc7-8d2f-a253074106e1",
    imgurl: "assets/images/van-bird-skull.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 67,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Midnight Tears",
    color: "silver",
    name: "Curved Barbell",
    pt_bone: "Helix Upper (R)",
    bone: "piercing_helix_a_r",
    location: "ears",
    nodeid: "eec50709-cbc4-4186-825b-3021d6921ff5",
    imgurl: "assets/images/van-horseshoe.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 68,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Silvergold Gala",
    color: "silver",
    name: "1 Spike Barbell",
    pt_bone: "Brow Upper (L)",
    bone: "piercing_brow_a_l",
    location: "brows",
    nodeid: "bfce578e-87ae-46ea-83ce-590bf0d08af8",
    imgurl: "assets/images/van-ballspike-bb.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 69,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Silvergold Gala",
    color: "silver",
    name: "Vanilla Flat Ring",
    pt_bone: "Nostril (R)",
    bone: "piercing_nostril_a_r",
    location: "nose",
    nodeid: "4a903b20-bf4a-4246-b134-3b8e5367ba07",
    imgurl: "assets/images/van-flat-ring-nose.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 70,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Silvergold Gala",
    color: "silver",
    name: "Studded Hoop",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "3b62f841-3d63-442b-98eb-1d013572f5f1",
    imgurl: "assets/images/van-studded-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 71,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Silvergold Gala",
    color: "silver",
    name: "Studded Hoop",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "ef0c9b0c-591f-4d76-86e1-454c71cac2d8",
    imgurl: "assets/images/van-studded-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 72,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Silvergold Gala",
    color: "silver",
    name: "Tusk Cuff",
    pt_bone: "Helix Upper (R)",
    bone: "piercing_helix_a_r",
    location: "ears",
    nodeid: "e9cdfcd5-3e91-436a-b532-c8fae22136d0",
    imgurl: "assets/images/van-tusk-cuff-u.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 73,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Silvergold Gala",
    color: "silver",
    name: "Tusk Cuff",
    pt_bone: "Helix Lower (R)",
    bone: "piercing_helix_b_r",
    location: "ears",
    nodeid: "da6968d9-5721-43a7-ac2a-282db7faf575",
    imgurl: "assets/images/van-tusk-cuff-l.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 74,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Silvergold Gala",
    color: "silver",
    name: "Pyramid Stud",
    pt_bone: "Nostril (L)",
    bone: "piercing_nostril_a_l",
    location: "nose",
    nodeid: "8361d543-3b97-4349-970c-57f5c4d75d82",
    imgurl: "assets/images/van-pyramid-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 75,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Darkmoons",
    color: "silver",
    name: "Tusk Dangle",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "36361726-8bdf-4dc0-ae64-a31de980b6aa",
    imgurl: "assets/images/van-tusk-dangle.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed7",
  },
  {
    index: 76,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Darkmoons",
    color: "silver",
    name: "Tusk Dangle",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "a67aa85d-7c65-42c2-ba5a-9f048a28a8f8",
    imgurl: "assets/images/van-tusk-dangle.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed8",
  },
  {
    index: 77,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Darkmoons",
    color: "silver",
    name: "Moon Stud",
    pt_bone: "Brow Upper (R)",
    bone: "piercing_brow_a_r",
    location: "brows",
    nodeid: "9876a6ee-6eea-4082-97cf-29b0f13d92cf",
    imgurl: "assets/images/van-moon-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed9",
  },
  {
    index: 78,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Darkmoons",
    color: "silver",
    name: "Ruby Gem Stud",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "df67fae5-0c76-4ba7-9f28-7a4cec6d7c43",
    imgurl: "assets/images/van-ruby-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed10",
  },
  {
    index: 79,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Darkmoons",
    color: "silver",
    name: "Ruby Gem Stud",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "9f089afe-c341-4451-8cd9-dc424f5fba2f",
    imgurl: "assets/images/van-ruby-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed11",
  },
  {
    index: 80,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Chultan Serpents",
    color: "silver",
    name: "Serpent Tail",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "172524be-a6cc-4204-b664-1d14b0a4ee62",
    imgurl: "assets/images/van-serpent-tail.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed12",
  },
  {
    index: 81,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Chultan Serpents",
    color: "silver",
    name: "Serpent Tail",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "45fcc7a1-4df9-498b-97a3-d2a52a21bbee",
    imgurl: "assets/images/van-serpent-tail.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed13",
  },
  {
    index: 82,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Crimsonhilt Dirks",
    color: "silver",
    name: "Dagger Dangle",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "33fb7410-0373-44ce-8652-4a213e1dc470",
    imgurl: "assets/images/van-dagger-dangle.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed14",
  },
  {
    index: 83,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Crimsonhilt Dirks",
    color: "silver",
    name: "Dagger Dangle",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "38be22d9-9dad-45a0-a38a-e8ccc8ba1f4e",
    imgurl: "assets/images/van-dagger-dangle.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed15",
  },
  {
    index: 84,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Barovia Fangs",
    color: "silver",
    name: "Spike Dangle",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "33167c69-56b3-463b-92ae-b57e02476bf8",
    imgurl: "assets/images/van-spike-dangle.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed18",
  },
  {
    index: 85,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Barovia Fangs",
    color: "silver",
    name: "Spike Dangle",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "46b34e71-1e91-48c2-81e7-8cb1532fbbb7",
    imgurl: "assets/images/van-spike-dangle.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed19",
  },
  {
    index: 86,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Barovia Fangs",
    color: "silver",
    name: "Vanilla Ring",
    pt_bone: "Helix Upper (L)",
    bone: "piercing_helix_a_l",
    location: "ears",
    nodeid: "f56063f5-e095-4687-b09a-ecfa12c3c8ec",
    imgurl: "assets/images/van-ring-hu.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed20",
  },
  {
    index: 87,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Barovia Fangs",
    color: "silver",
    name: "Vanilla Ring",
    pt_bone: "Helix Lower (L)",
    bone: "piercing_helix_b_l",
    location: "ears",
    nodeid: "5bf9050a-4c43-4847-ae89-10b7b20a95dd",
    imgurl: "assets/images/van-ring-hl.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed21",
  },
  {
    index: 88,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Barovia Fangs",
    color: "silver",
    name: "Vanilla Ring",
    pt_bone: "Lobe Upper (R)",
    bone: "piercing_lobe_b_r",
    location: "ears",
    nodeid: "fd57b4cc-98c4-40c4-91dc-ede0267ccdfd",
    imgurl: "assets/images/van-ring-lu.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed22",
  },
  {
    index: 89,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Barovia Fangs",
    color: "silver",
    name: "Leaf Stud",
    pt_bone: "Tragus (L)",
    bone: "piercing_tragus_a_l",
    location: "ears",
    nodeid: "b53c1e5f-e000-45ae-82f2-e5c28b5676be",
    imgurl: "assets/images/van-leaf-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed23",
  },
  {
    index: 90,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Barovia Fangs",
    color: "silver",
    name: "Leaf Stud",
    pt_bone: "Tragus (R)",
    bone: "piercing_tragus_a_r",
    location: "ears",
    nodeid: "04e1515b-65b3-4994-a383-f3fb3e49cc54",
    imgurl: "assets/images/van-leaf-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed24",
  },
  {
    index: 91,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Minotaur Ring",
    color: "silver",
    name: "Skull Ring",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "c84ed6bb-f3d3-4d8f-b9c2-2812f0dcd111",
    imgurl: "assets/images/van-skull-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed25",
  },
  {
    index: 92,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Easy Breezy",
    color: "silver",
    name: "Skull Ring",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "46f339ee-f5ee-460e-9526-9d0884d9926c",
    imgurl: "assets/images/van-skull-ring-l.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed26",
  },
  {
    index: 93,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Easy Breezy",
    color: "silver",
    name: "Skull Stud",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "d12af7cf-c29a-4ed9-ba44-6f694f4e04d5",
    imgurl: "assets/images/van-skull-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed27",
  },
  {
    index: 94,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Archfey Swirls",
    color: "silver",
    name: "Fancy Leaf Swirl",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "870f197a-54dd-4aac-ab32-b21ca66e832f",
    imgurl: "assets/images/van-leaf-swirl.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed28",
  },
  {
    index: 95,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Archfey Swirls",
    color: "silver",
    name: "Fancy Leaf Swirl",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "75c9dcff-62e6-41b8-bac4-42be78e96913",
    imgurl: "assets/images/van-leaf-swirl.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed29",
  },
  {
    index: 96,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Commoner Ring",
    color: "silver",
    name: "Ring with Ball",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "086bfc03-927c-43ce-a818-3db3b8ba80ab",
    imgurl: "assets/images/van-ring-ball-nose.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed30",
  },
  {
    index: 97,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Bard Rings",
    color: "silver",
    name: "Ring with Ball",
    pt_bone: "Helix Upper (L)",
    bone: "piercing_helix_a_l",
    location: "ears",
    nodeid: "427012ca-9b18-424c-8ee9-a59ff55b152e",
    imgurl: "assets/images/van-ring-ball-hu.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed31",
  },
  {
    index: 98,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Bard Rings",
    color: "silver",
    name: "Ring with Ball",
    pt_bone: "Helix Lower (L)",
    bone: "piercing_helix_b_l",
    location: "ears",
    nodeid: "79ae4309-bd93-4620-b0d6-a80bb7e7e8a4",
    imgurl: "assets/images/van-ring-ball-hl.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed32",
  },
  {
    index: 99,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Bard Rings",
    color: "silver",
    name: "Ring with Ball",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "3248f9d5-05cc-42f8-a111-772f894439a7",
    imgurl: "assets/images/van-ring-ball-ll.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed33",
  },
  {
    index: 100,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Bard Rings",
    color: "silver",
    name: "Ring with Ball",
    pt_bone: "Lobe Upper (L)",
    bone: "piercing_lobe_b_l",
    location: "ears",
    nodeid: "514dcb13-e15f-4cb0-94a2-cf22d9cf2965",
    imgurl: "assets/images/van-ring-ball-lu.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed34",
  },
  {
    index: 101,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Bard Rings",
    color: "silver",
    name: "Ring with Ball",
    pt_bone: "Helix Upper (R)",
    bone: "piercing_helix_a_r",
    location: "ears",
    nodeid: "e4998190-4621-4de6-a49b-8e43d751c074",
    imgurl: "assets/images/van-ring-ball-hu.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed35",
  },
  {
    index: 102,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Bard Rings",
    color: "silver",
    name: "Ring with Ball",
    pt_bone: "Helix Lower (R)",
    bone: "piercing_helix_b_r",
    location: "ears",
    nodeid: "be72fe8d-a81a-4459-a637-344f4e508ac7",
    imgurl: "assets/images/van-ring-ball-hl.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed36",
  },
  {
    index: 103,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Bard Rings",
    color: "silver",
    name: "Ring with Ball",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "43e7eb3d-ca85-42b9-b32d-ad1be18d1001",
    imgurl: "assets/images/van-ring-ball-ll.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed37",
  },
  {
    index: 104,
    site_cat: "vanilla-ab",
    type: "vanilla",
    set_name: "Bard Rings",
    color: "silver",
    name: "Ring with Ball",
    pt_bone: "Lobe Upper (R)",
    bone: "piercing_lobe_b_r",
    location: "ears",
    nodeid: "ae1ce151-6944-435a-a616-30c4d59bfb31",
    imgurl: "assets/images/van-ring-ball-lu.jpg",
    selected: false,
    disabled: false,
    matcat: "set-b",
    matid: "fc211abc-b97d-b3d8-5241-cd2055f43ed38",
  },
  {
    index: 105,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Fine Ring",
    pt_bone: "Nostril (L)",
    bone: "piercing_nostril_a_l",
    location: "nose",
    nodeid: "77d0aabc-f14d-4b0f-bd1e-8db90e50bfb5",
    imgurl: "assets/images/isp-ring-nostril-l.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 106,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Fine Ring",
    pt_bone: "Nostril (R)",
    bone: "piercing_nostril_a_r",
    location: "nose",
    nodeid: "3a240fbd-981c-42c0-8b65-c188c5095eb9",
    imgurl: "assets/images/isp-ring-nostril-r.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 107,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Fine Ring",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "5f1506ad-3571-47de-a00b-2340e27cc5f8",
    imgurl: "assets/images/isp-ring-septum.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 108,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Ball Stud",
    pt_bone: "Monroe (L)",
    bone: "beard_upper_lip1_l",
    location: "lips",
    nodeid: "335d855e-41c5-4473-8fde-eb32469ad925",
    imgurl: "assets/images/isp-monroe.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 109,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Ball Stud",
    pt_bone: "Monroe (R)",
    bone: "beard_upper_lip1_r",
    location: "lips",
    nodeid: "45edc575-a5ff-4b3c-945f-e178394784c3",
    imgurl: "assets/images/isp-monroe.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 110,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Disc Stud",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "0180d546-929d-4e9e-867e-ee5f647fcbfa",
    imgurl: "assets/images/isp-disc-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 111,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Disc Stud",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "bcfab042-3461-4999-a7eb-0934b41066f7",
    imgurl: "assets/images/isp-disc-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 112,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Horseshoe Ring",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "19b31268-9758-46d8-a90e-fb9afae7ab49",
    imgurl: "assets/images/isp-horseshoe.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 113,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Ball Stud",
    pt_bone: "Labret (M)",
    bone: "lowerlip_06",
    location: "lips",
    nodeid: "70d706f4-177a-48b7-b1aa-36ff8409f8f6",
    imgurl: "assets/images/isp-ball-labret.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 114,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Ball Stud",
    pt_bone: "Nostril (L)",
    bone: "piercing_nostril_a_l",
    location: "nose",
    nodeid: "3ed371f7-fc60-4646-adff-b10c07c95c5a",
    imgurl: "assets/images/isp-ball-nostril-l.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 115,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Ball Stud",
    pt_bone: "Nostril (R)",
    bone: "piercing_nostril_a_r",
    location: "nose",
    nodeid: "78c51608-641c-4e5e-8e20-af639ccccbf8",
    imgurl: "assets/images/isp-ball-nostril-r.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 116,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Ball Stud",
    pt_bone: "Medusa",
    bone: "beard_upper_lip_m",
    location: "lips",
    nodeid: "9c95efc0-838c-4fbd-a84c-93a2f744813c",
    imgurl: "assets/images/isp-ball-medusa.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 117,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Horizontal Barbell",
    pt_bone: "Brow Upper (L)",
    bone: "piercing_brow_a_l",
    location: "brows",
    nodeid: "963e7416-9444-4264-b15b-cf1717016cec",
    imgurl: "assets/images/isp-hor-bb.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 118,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Horizontal Barbell",
    pt_bone: "Brow Upper (R)",
    bone: "piercing_brow_a_r",
    location: "brows",
    nodeid: "83a481c0-cf8e-4bee-afc4-42c6e16e5557",
    imgurl: "assets/images/isp-hor-bb.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 119,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Double Ball Studs",
    pt_bone: "Labret (L)",
    bone: "lowerlip_08",
    location: "lips",
    nodeid: "b9f9f8bb-cd1d-4c8a-bcbf-1d3390929ef4",
    imgurl: "assets/images/isp-spiderbites-l.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 120,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Double Ball Studs",
    pt_bone: "Labret (R)",
    bone: "lowerlip_04",
    location: "lips",
    nodeid: "a70b1a34-c1b1-4793-a8fd-5f649c469b81",
    imgurl: "assets/images/isp-spiderbites-r.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 121,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Ball Stud",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "b9874322-9a39-43fb-bd1f-c498e2e2bc34",
    imgurl: "assets/images/isp-ball-lobe.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 122,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Ball Stud",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "803bc5ab-8c1b-4f3c-907f-fc7a6b10e6a6",
    imgurl: "assets/images/isp-ball-lobe.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 123,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Eagle Ring",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "934c6a42-55cd-48d7-ace7-3af71d316d79",
    imgurl: "assets/images/isp-eagle-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 124,
    site_cat: "isp_silver",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "silver",
    name: "Eagle Ring",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "8a5c7e5d-4591-46b9-a623-55674a3420c6",
    imgurl: "assets/images/isp-eagle-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "set-a",
    matid: "ff3eeaa1-454f-2053-8bbc-be7832c420dd",
  },
  {
    index: 125,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Fine Ring",
    pt_bone: "Nostril (L)",
    bone: "piercing_nostril_a_l",
    location: "nose",
    nodeid: "fb0d3223-bb64-4db3-82e2-2f72b2cf4dfc",
    imgurl: "assets/images/gold/isp-ring-nostril-l.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 126,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Fine Ring",
    pt_bone: "Nostril (R)",
    bone: "piercing_nostril_a_r",
    location: "nose",
    nodeid: "116d8a8d-d063-49bd-a565-c282c493c021",
    imgurl: "assets/images/gold/isp-ring-nostril-r.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 127,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Fine Ring",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "fc7e1129-caa8-4449-af16-f7c8c4ad5b0f",
    imgurl: "assets/images/gold/isp-ring-septum.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 128,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Ball Stud",
    pt_bone: "Monroe (L)",
    bone: "beard_upper_lip1_l",
    location: "lips",
    nodeid: "01aeaf1b-800c-4875-b02c-0dd3ea91fd74",
    imgurl: "assets/images/gold/isp-monroe.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 129,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Ball Stud",
    pt_bone: "Monroe (R)",
    bone: "beard_upper_lip1_r",
    location: "lips",
    nodeid: "8f940c15-1b79-43c9-bb75-22d0b290f2a0",
    imgurl: "assets/images/gold/isp-monroe.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 130,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Green Disc Stud",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "67045df9-9bab-42bc-ae26-a385bf330ba7",
    imgurl: "assets/images/gold/isp-disc-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 131,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Green Disc Stud",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "d56c4e65-78cf-4c14-b8d5-cc58fd3625c2",
    imgurl: "assets/images/gold/isp-disc-stud.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 132,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Horseshoe Ring",
    pt_bone: "Septum",
    bone: "piercing_septum_a_m",
    location: "nose",
    nodeid: "b2908f02-4d8a-457a-a8f8-599ef268feba",
    imgurl: "assets/images/gold/isp-horseshoe.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 133,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Ball Stud",
    pt_bone: "Labret (M)",
    bone: "lowerlip_06",
    location: "lips",
    nodeid: "a0bc63a3-611a-4986-b775-6dcd2ec062d2",
    imgurl: "assets/images/gold/isp-ball-labret.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 134,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Ball Stud",
    pt_bone: "Nostril (L)",
    bone: "piercing_nostril_a_l",
    location: "nose",
    nodeid: "c85230a1-f12d-408c-9e74-0052545935f9",
    imgurl: "assets/images/gold/isp-ball-nostril-l.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 135,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Ball Stud",
    pt_bone: "Nostril (R)",
    bone: "piercing_nostril_a_r",
    location: "nose",
    nodeid: "91d2862b-a6e7-4994-a18a-f94e08f49be2",
    imgurl: "assets/images/gold/isp-ball-nostril-r.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 136,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Ball Stud",
    pt_bone: "Medusa",
    bone: "beard_upper_lip_m",
    location: "lips",
    nodeid: "56db542c-e024-45fa-b33f-7d81e15b1d9e",
    imgurl: "assets/images/gold/isp-ball-medusa.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 137,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Horizontal Barbell",
    pt_bone: "Brow Upper (L)",
    bone: "piercing_brow_a_l",
    location: "brows",
    nodeid: "72e0a06b-1625-4fb6-9678-60fc8fad63f4",
    imgurl: "assets/images/gold/isp-hor-bb.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 138,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Horizontal Barbell",
    pt_bone: "Brow Upper (R)",
    bone: "piercing_brow_a_r",
    location: "brows",
    nodeid: "f83cc26c-250a-4f81-b40e-cf7cc3316a11",
    imgurl: "assets/images/gold/isp-hor-bb.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 139,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Double Ball Studs",
    pt_bone: "Labret (L)",
    bone: "lowerlip_08",
    location: "lips",
    nodeid: "f19da301-3a7b-4592-bf88-ae6597326daa",
    imgurl: "assets/images/gold/isp-spiderbites-l.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 140,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Double Ball Studs",
    pt_bone: "Labret (R)",
    bone: "lowerlip_04",
    location: "lips",
    nodeid: "c85a022a-709d-430c-b113-51d0ca502473",
    imgurl: "assets/images/gold/isp-spiderbites-r.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 141,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Ball Stud",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "c54a57f5-d5f6-4641-8bcd-4972df5d2fee",
    imgurl: "assets/images/gold/isp-ball-lobe.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 142,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Ball Stud",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "2e8de976-24c1-4c79-80c0-82593f4a2c13",
    imgurl: "assets/images/gold/isp-ball-lobe.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 143,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Eagle Ring",
    pt_bone: "Lobe Lower (L)",
    bone: "piercing_lobe_a_l",
    location: "ears",
    nodeid: "4361f318-2111-474a-a02d-6db03d1d8081",
    imgurl: "assets/images/gold/isp-eagle-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
  {
    index: 144,
    site_cat: "isp_gold",
    type: "mod",
    set_name: "Indoct's Subtler Piercings",
    color: "gold",
    name: "Eagle Ring",
    pt_bone: "Lobe Lower (R)",
    bone: "piercing_lobe_a_r",
    location: "ears",
    nodeid: "5b7bcaa5-56f5-43af-b440-e9a2f8190150",
    imgurl: "assets/images/gold/isp-eagle-ring.jpg",
    selected: false,
    disabled: false,
    matcat: "isp-gold",
    matid: "4ecf0e10-d34a-42dd-ba88-85627ec8655c",
  },
];

export const config = {
  lowerlip_04: "",
  lowerlip_06: "",
  lowerlip_08: "",
  beard_upper_lip_m: "",
  beard_upper_lip1_l: "",
  beard_upper_lip1_r: "",
  piercing_bridge_a_l: "",
  piercing_bridge_a_r: "",
  piercing_brow_a_l: "",
  piercing_brow_a_r: "",
  piercing_brow_b_l: "",
  piercing_brow_b_r: "",
  piercing_helix_a_l: "",
  piercing_helix_a_r: "",
  piercing_helix_b_l: "",
  piercing_helix_b_r: "",
  piercing_lobe_a_l: "",
  piercing_lobe_a_r: "",
  piercing_lobe_b_l: "",
  piercing_lobe_b_r: "",
  piercing_nostril_a_l: "",
  piercing_nostril_a_r: "",
  piercing_septum_a_m: "",
  piercing_tragus_a_l: "",
  piercing_tragus_a_r: "",
};
